import type { Card, Category } from '../types.js'

const CATEGORY_ASSET_FOLDERS: Record<Category, string> = {
  people: 'การ์ดหมวด People',
  prosperity: 'การ์ดหมวด Prosperity',
  planet: 'การ์ดหมวด Planet',
  peace: 'การ์ดหมวด Peace',
  partnership: 'การ์ดหมวด Partnership',
}

const build = (category: Category, rows: Array<[string, string, string]>): Card[] =>
  rows.map(([icon, text, textEn], index) => ({
    id: `${category}-${String(index + 1).padStart(2, '0')}`,
    category,
    icon,
    image: `/assets/cards/${CATEGORY_ASSET_FOLDERS[category]}/${String(index + 1).padStart(2, '0')}-${text}.png`,
    text,
    textEn,
  }))

export const CARDS: Card[] = [
  ...build('people', [
    ['🍲', 'ยิ้ม ทักทาย เพื่อนข้างบ้านบ้างในโอกาสที่เหมาะสม', 'Smile and greet your neighbors when the moment feels right'],
    ['🧓', 'ไปเยี่ยมและนำของไปให้ผู้สูงอายุในชุมชน', 'Visit older people in your community and bring them something thoughtful'],
    ['📚', 'สอนการบ้านให้เด็กในละแวกบ้าน', 'Help children in your neighborhood with their homework'],
    ['🩹', 'เรียนปฐมพยาบาลเบื้องต้น', 'Learn basic first aid'],
    ['🎧', 'เป็นคนเข้าอกเข้าใจ เป็นที่ปรึกษาของเพื่อนเสมอ', 'Be an empathetic friend who is always ready to listen'],
    ['🚸', 'หยุดรถทางม้าลายสม่ำเสมอแม้ไม่มีคนรอข้าม', 'Always stop at pedestrian crossings, even when no one is waiting'],
    ['🏥', 'พาญาติไปตรวจสุขภาพประจำปี', 'Take a family member for an annual health checkup'],
    ['🤱', 'ช่วยเพื่อนร่วมงานที่เพิ่งลาคลอด', 'Support a coworker who has just returned from maternity leave'],
    ['♿', 'เปิดทางให้คนพิการก่อน', 'Give people with disabilities space to go first'],
    ['🧑‍🍳', 'เข้าร่วมอาสาสมัครมูลนิธิช่วยคนเจ็บป่วย', 'Volunteer with a foundation that supports people who are ill'],
    ['💬', 'ริเริ่มชวนคุยเพื่อนใหม่ในที่ทำงาน', 'Start a conversation with a new colleague'],
    ['🩺', 'บริจาคเลือด', 'Donate blood'],
    ['🧸', 'บริจาคของเล่นให้เด็กด้อยโอกาส', 'Donate toys to underprivileged children'],
    ['🗣️', 'ชอบพูดให้กำลังใจผู้คนอยู่เสมอ', 'Regularly encourage and uplift others'],
    ['👨‍👩‍👧', 'ใช้เวลากับครอบครัวโดยไม่เล่นมือถือ', 'Spend time with family without using your phone'],
    ['🧑‍🏫', 'เป็นอาสาสอนหนังสือวันเสาร์', 'Volunteer to teach on Saturdays'],
  ]),
  ...build('prosperity', [
    ['💡', 'ลองทำไอเดียธุรกิจเล็กๆ ของตัวเอง', 'Try bringing a small business idea of your own to life'],
    ['🛍️', 'ซื้อของจากร้านค้าชุมชนแทนห้างใหญ่', 'Shop at local community stores instead of large chains'],
    ['📈', 'เก็บออมเงินเดือนละเล็กน้อย', 'Save a little money each month'],
    ['🎓', 'เรียนทักษะใหม่หลังเลิกงาน', 'Learn a new skill after work'],
    ['🤝', 'ช่วยแนะนำงานให้คนตกงาน', 'Help connect someone who is unemployed with a job opportunity'],
    ['🧵', 'สนับสนุนสินค้าฝีมือคนในพื้นที่', 'Support locally made products'],
    ['💻', 'สอนทักษะดิจิทัลให้คนรุ่นพ่อแม่', 'Teach digital skills to older generations'],
    ['🌾', 'ซื้อผลผลิตตรงจากเกษตรกร', 'Buy produce directly from farmers'],
    ['🏪', 'อุดหนุนร้านค้าเล็กๆ ที่เพิ่งเปิดใหม่', 'Support a small shop that has just opened'],
    ['📊', 'วางแผนการเงินให้คนในครอบครัว', 'Help your family plan their finances'],
    ['🔧', 'ซ่อมของใช้เองแทนซื้อใหม่', 'Repair things instead of buying new ones'],
    ['🚀', 'ลงทุนเวลากับงานอดิเรกที่สร้างรายได้', 'Invest time in a hobby that can earn income'],
    ['🧑‍🌾', 'สนับสนุนสหกรณ์ในชุมชน', 'Support a community cooperative'],
    ['💳', 'ใช้จ่ายอย่างมีสติ ไม่เป็นหนี้เกินตัว', 'Spend mindfully and avoid taking on too much debt'],
    ['🎨', 'ขายงานฝีมือที่ตัวเองทำ', 'Sell crafts you make yourself'],
    ['🌐', 'เรียนรู้เทคโนโลยีใหม่ๆ ที่ช่วยงาน', 'Learn new technology that can help you work better'],
  ]),
  ...build('planet', [
    ['🌱', 'ปลูกผักกินเองที่บ้าน', 'Grow vegetables at home'],
    ['🚲', 'เดินหรือปั่นจักรยานแทนขับรถ', 'Walk or cycle instead of driving'],
    ['💧', 'ปิดน้ำระหว่างแปรงฟัน', 'Turn off the tap while brushing your teeth'],
    ['♻️', 'แยกขยะก่อนทิ้ง', 'Sort your waste before throwing it away'],
    ['🔌', 'ถอดปลั๊กเครื่องใช้ไฟฟ้าที่ไม่ใช้', 'Unplug electrical appliances when they are not in use'],
    ['🌳', 'ปลูกต้นไม้ในพื้นที่ว่าง', 'Plant trees in unused spaces'],
    ['🍃', 'ลดใช้พลาสติกครั้งเดียวทิ้ง', 'Reduce single-use plastic'],
    ['☀️', 'ใช้แสงแดดแทนเปิดไฟกลางวัน', 'Use daylight instead of turning on lights during the day'],
    ['🥗', 'กินผักผลไม้ตามฤดูกาล', 'Eat seasonal fruit and vegetables'],
    ['🧴', 'เลือกใช้ผลิตภัณฑ์แบบใช้ซ้ำได้', 'Choose reusable products'],
    ['🐝', 'ปลูกดอกไม้ที่ดึงความสนใจผึ้ง', 'Plant flowers that attract bees'],
    ['🚯', 'เก็บขยะที่เจอระหว่างทาง', 'Pick up litter you find along the way'],
    ['🌊', 'ไม่ทิ้งขยะลงสู่แม่น้ำลำคลอง', 'Never throw rubbish into rivers or canals'],
    ['🧺', 'นำน้ำจากการซักล้างไปรดน้ำต้นไม้', 'Reuse household wastewater to water plants'],
    ['🍽️', 'กินอาหารให้หมดจาน ไม่เหลือทิ้ง', 'Finish your food and avoid waste'],
    ['🌤️', 'เดินขึ้นบันไดแทนลิฟต์ช่วงชั้นใกล้', 'Take the stairs instead of the lift for nearby floors'],
  ]),
  ...build('peace', [
    ['🕊️', 'ไกล่เกลี่ยเวลาเพื่อนทะเลาะกัน', 'Help mediate when friends argue'],
    ['👂', 'รับฟังความเห็นต่างโดยไม่ตัดสิน', 'Listen to different opinions without judging'],
    ['🙏', 'ให้อภัยคนที่เคยทำผิดพลาด', 'Forgive someone who has made a mistake'],
    ['🚦', 'ขับรถอย่างมีน้ำใจ ไม่แซงปาดหน้า', 'Drive considerately and do not cut others off'],
    ['🧘', 'คิดก่อนโต้ตอบด้วยวาจารุนแรง', 'Think before responding with harsh words'],
    ['🏳️', 'เคารพความแตกต่างทางความเชื่อ', 'Respect differences in belief'],
    ['🤲', 'รับคำขอโทษอย่างจริงใจ', 'Accept a sincere apology'],
    ['🔇', 'ไม่นินทาคนลับหลัง', 'Do not gossip behind others’ backs'],
    ['📵', 'ลดละการตอบโต้ในโลกสังคมออนไลน์', 'Avoid arguing on social media'],
    ['🧑‍⚖️', 'เคารพกฎกติกาส่วนรวม', 'Respect shared rules'],
    ['🕯️', 'ร่วมกิจกรรมรำลึกเพื่อความสมานฉันท์', 'Join remembrance activities that promote reconciliation'],
    ['🚪', 'เปิดใจคุยกับคนที่เคยขัดแย้ง', 'Open up a conversation with someone you have had conflict with'],
    ['🧩', 'หาจุดร่วมแทนเอาชนะกันในที่ประชุม', 'Look for common ground instead of trying to win in meetings'],
    ['🛑', 'กล้าหยุดความรุนแรงรอบตัว', 'Speak up to stop violence around you'],
    ['🌈', 'ยอมรับความหลากหลายในที่ทำงาน', 'Embrace diversity in the workplace'],
    ['🤝', 'ขอโทษก่อนเมื่อรู้ตัวว่าผิด', 'Apologize first when you realize you were wrong'],
  ]),
  ...build('partnership', [
    ['🤝', 'รวมกลุ่มเพื่อนบ้านทำกิจกรรมส่วนรวม', 'Bring neighbors together for a community activity'],
    ['📣', 'ชวนเพื่อนมาร่วมโครงการอาสา', 'Invite friends to join a volunteer project'],
    ['🔄', 'แลกเปลี่ยนของใช้กับเพื่อนบ้านแทนซื้อใหม่', 'Swap useful items with neighbors instead of buying new ones'],
    ['🧑‍🤝‍🧑', 'บูรณาการงานกับหลายแผนก', 'Collaborate across different departments'],
    ['🏘️', 'ตั้งกลุ่มไลน์ดูแลความปลอดภัยหมู่บ้าน', 'Create a neighborhood LINE group for community safety'],
    ['📦', 'เที่ยวประจำปีกับเพื่อนเก่า', 'Take an annual trip with old friends'],
    ['🎪', 'ช่วยกันจัดงานชุมชน', 'Help organize a community event'],
    ['🧠', 'แชร์ความรู้ที่ตัวเองมีให้คนอื่นฟรี', 'Share your knowledge with others for free'],
    ['🚨', 'แจ้งเตือนเพื่อนบ้านเมื่อพบปัญหา', 'Alert neighbors when you notice a problem'],
    ['🏫', 'ร่วมมือกับโรงเรียนจัดกิจกรรมเด็ก', 'Partner with a school to organize activities for children'],
    ['🌉', 'เชื่อมสองทีมที่ไม่เคยคุยกันให้รู้จักกัน', 'Introduce two teams that have never worked together'],
    ['🤲', 'ระดมทุนช่วยคนที่เดือดร้อน', 'Raise funds for people in need'],
    ['📱', 'ใช้แอปกลางแชร์ของเหลือใช้ในชุมชน', 'Use a shared app to pass surplus items around the community'],
    ['🧺', 'ร่วมงานสังสรรค์กับแผนกหรือที่ทำงาน', 'Join a social gathering with your department or workplace'],
    ['🗳️', 'ร่วมเสียงเสนอความเห็นต่อนโยบายท้องถิ่น', 'Add your voice to local policy discussions'],
    ['🌾', 'แชร์รถกับเพื่อนไปทำงาน', 'Carpool with friends to work'],
  ]),
]
